version: '3.5'

services:
  nginx:
    build: ./docker/nginx
    volumes:
      - php-fpm-run:/var/run/php-fpm
      - htdocs:/usr/local/site
    ports:
      - "8000:80"

  mariadb:
    build: ./docker/mariadb
    volumes:
      - mariadb-run:/var/lib/mysql

  wordpress:
    build: ./docker/wordpress
    depends_on:
      - nginx
      - mariadb
    volumes:
      - mariadb-run:/usr/local/mysql
      - php-fpm-run:/var/run/php-fpm
      - htdocs:/usr/local/site

volumes:
  htdocs:
  php-fpm-run:
  mariadb-run:
