version: '3.5'

services:
  nginx:
    build: ./docker/nginx
    depends_on:
      - wordpress
    volumes:
      - php-fpm-run:/var/run/php-fpm
      - htdocs:/usr/local/site
      - ./dist:/usr/local/site/wp-content/themes/my-theme
    ports:
      - "8000:80"

  mariadb:
    build: ./docker/mariadb
    volumes:
      - mariadb-run:/var/lib/mysql

  wordpress:
    build: ./docker/wordpress
    depends_on:
      - mariadb
    volumes:
      - mariadb-run:/usr/local/mysql
      - php-fpm-run:/var/run/php-fpm
      - htdocs:/usr/local/site
      - ./dist:/usr/local/site/wp-content/themes/my-theme
    env_file:
      - wordpress.env

volumes:
  htdocs:
  php-fpm-run:
  mariadb-run:
